### ISSUE TITLE
SitewaertsDocumentViewer.viewDocument function is not working in android 7 

### ISSUE THREAD

**Issue by rameshsharmaaspire** [sitewaerts/cordova-plugin-document-viewer#61] opened 2017-04-10 07:08 UTC
I am Getting this error in android 7 -

sitewaertsdocumentviewer.js:302 Error in SitewaertsDocumentViewer.viewDocument():  file:///storage/emulated/0/Android/data/com.abc.sample/files/resume.pdf exposed beyond app through Intent.getData()

It is due to android 7 restriction to file:// uri access as per new security norms.

please guide me to fix this in android 7.I went to several resources and They all suggests to implement file provider but when I change export = true in androidManifest my application gets crash.

Thanks.

**Comment by regnete** [comment] 2017-04-12 07:23
cab you reproduce the issue on a physical device or in an emulator only?

**Comment by rameshsharmaaspire** [comment] 2017-04-12 07:40
The issue was in physical device. I fixed it by using google doc app instead of cleverdox to open doc and pdf files. The thing was when we use File Provider class instead of file uri(as android 7 does not allow file uri for security reason) we get permission denial Error for cleaverdox package. google doc app package is having permission in plugin  so we can open that by specifying google doc package and its activity in options.

**Comment by regnete** [comment] 2017-04-12 08:47
So this is a bug in the https://github.com/sitewaerts/android-document-viewer?  We just need to adjust the app permissions and publish an new version of the app in google play?

**Comment by rameshsharmaaspire** [comment] 2017-04-12 09:01
May be yes. I am not Android developer. I tried to give permission but in
vain. Using Google doc package and it's activity worked for me.

But other than this cordova-document-viewer plugin must use file provider
for Android 7.




On Apr 12, 2017 2:17 PM, "Felix Schauerte" <notifications@github.com> wrote:

So this is a bug in the https://github.com/sitewaerts/
android-document-viewer? We just need to adjust the app permissions and
publish an new version of the app in google play?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sitewaerts/cordova-plugin-document-viewer/issues/61#issuecomment-293513699>,
or mute the thread

**Comment by regnete** [comment] 2017-04-12 13:18
Looks like the MUPDF Impl we are using had (or still has) problems accessing files specified via content uris. Thats why we decided to use file uris. 

we will check if migration to content uris is possible.

**Comment by regnete** [comment] 2017-04-12 14:36
cordova-plugin-document-viewer only supports pdf files in ios, android and windows. support for doc is not planned. try onne of the varios "open file in app" cordova plugins to open a doc file in e.g. ms office app.

**Comment by adam187** [comment] 2017-04-18 11:34
Similar issues was resolved for cordova-plugin-file-opener2  recently (https://github.com/pwlin/cordova-plugin-file-opener2/issues/84).  
It was fixed in https://github.com/pwlin/cordova-plugin-file-opener2/pull/89 
Maybe this will help fix issue here also.

**Comment by rameshsharmaaspire** [comment] 2017-04-18 12:43
Thanks.

On Apr 18, 2017 5:04 PM, "Adam Misiorny" <notifications@github.com> wrote:

Similar issues was resolved for cordova-plugin-file-opener2 recently (
pwlin/cordova-plugin-file-opener2#84
<https://github.com/pwlin/cordova-plugin-file-opener2/issues/84>).
It was fixed in pwlin/cordova-plugin-file-opener2#89
<https://github.com/pwlin/cordova-plugin-file-opener2/pull/89>
Maybe this will help fix issue here also.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sitewaerts/cordova-plugin-document-viewer/issues/61#issuecomment-294797020>,
or mute the thread

**Comment by regnete** [comment] 2017-05-03 06:49
It works on my brand new Pixel C with Android 7.1.1.
@rameshsharmaaspire: Which Hardware and OS are you running on? How can I reproduce the described behaviour?

**Comment by regnete** [comment] 2017-05-03 08:18
Could you please provide your apps config.xml?  My app (which works on Android 7) uses the following settings:
```
         <!-- Android 4.2 JELLY_BEAN  -->
        <preference name="android-minSdkVersion" value="16"/>
        <!-- Android 4.4.2 -->
        <preference name="android-targetSdkVersion" value="19"/>
        <!--<preference name="android-installLocation" value="internalOnly"/>-->
        <preference name="android-manifest/@android:installLocation" value="internalOnly"/>
```

**Comment by rameshsharmaaspire** [comment] 2017-05-03 08:50
@regnete  Looks like you are restricting target sdk to 19 which is not android 7 sdk. Its api 25 for android 7.You can reproduce error when you use target sdk greater than 23.

In my config.xml I have added only this.
                         <preference name="android-minSdkVersion" value="16" />

In AndroidManifest.xml.

                         <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="25" />

I fixed the issue by using making app open Google doc instead of cleverdox.

**Comment by regnete** [comment] 2017-05-03 14:04
Building with <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="25" /> and running on an Android 6.0.1 device works fine.

Will try to run it on an Android 7 device soon.

**Comment by regnete** [comment] 2017-05-09 11:54
Fixed in version 0.9.0.
Attention: Users MUST install version >= 1.3.0 of the cleverdox viewer app from google play. This was published momenhts ago and will be available within the next hours.

**Comment by regnete** [comment] 2017-05-09 12:39
0.9.0 is buggy. Fixed in 0.9.1.

**Comment by stacybrenes** [comment] 2017-05-25 15:51
Hi, 

We are trying to apply your fix, however v.1.3.0 has not been released to the Play Store. Do you have a timeline as to when this will be released?

-Stacy

**Comment by regnete** [comment] 2017-05-26 09:34
Hi Stacy,

as I know cleverdox Viewer 1.3.0 is already available at google play. Some elder android versions will load the prior version ss 1.3.0 doesn't support all android versions.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 25.05.2017 um 17:51 schrieb stacybrenes <notifications@github.com<mailto:notifications@github.com>>:


Hi,

We are trying to apply your fix, however v.1.3.0 has not been released to the Play Store. Do you have a timeline as to when this will be released?

-Stacy

-

**Comment by regnete** [comment] 2017-05-26 09:36
Hi Stacy,

I won't be able to investigate in this issue before 6th of june.

Felix


Am 25.05.2017 um 17:51 schrieb stacybrenes <notifications@github.com<mailto:notifications@github.com>>:


Hi,

We are trying to apply your fix, however v.1.3.0 has not been released to the Play Store. Do you have a timeline as to when this will be released?

-Stacy

-

**Comment by stacybrenes** [comment] 2017-05-26 14:57
We are not using elder versions of android, we are testing on a  Google Pixel running Android 7.1.2.

**Comment by regnete** [comment] 2017-05-26 16:06
that is exactly our dev setup. i will come back to you after 6th of june with solution for this issue.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 26.05.2017 um 16:58 schrieb stacybrenes <notifications@github.com<mailto:notifications@github.com>>:


We are not using elder versions of android, we are testing on a Google Pixel running Android 7.1.2.

-

**Comment by regnete** [comment] 2017-06-06 08:07
@stacybrenes cleverdox Viewer 1.2.0 (NOT 1.3.0) contains the fix! My fault! Sorry. Di you hve any issues with that version?

**Comment by stacybrenes** [comment] 2017-06-06 17:01
Yes. We were unable to get the 1.3.0 version and 1.2.0 cannot open the PDF's

**Comment by regnete** [comment] 2017-06-08 12:05
can you reproduce the issue with the sample app (https://github.com/sitewaerts/cordova-plugin-document-viewer-sample-app)?

**Comment by regnete** [comment] 2017-07-06 06:35
Any news on this issue?
will close it otherwise.

**Closed** 2017-10-16 07:09 UTC
Labels: bug, Platform: Android

**Comment by Ross-Rawlins** [comment] 2018-04-11 07:53
I am still geting this

**Comment by mchulet** [comment] 2018-06-26 11:41
Still having this issue.
