### ISSUE TITLE
:transformClassesWithDexForDebug Error ionic v1

### ISSUE THREAD

**Issue by Amit06** [sitewaerts/cordova-plugin-document-viewer#70] opened 2017-06-08 02:08 UTC
I am using this plugin in an ionic v1 app and this plugin also installs cordova-plugin-android-support-v4-jar 23.2.1 whic causes trouble and :transformClassesWithDexForDebug error occours 

Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

**Comment by regnete** [comment] 2017-06-08 08:14
Issue may be caused by ionic or another plugin you use in your project. Does the issue persist if you remove all other plugins from your project (should be easy to test as its a compile/build time issue)? 

I guess the error indicates to different versions of android-support-v4.jar. Sorry, but I don't have any experiences with ionic. Is anybody out there who knows how to deal with this?

**Comment by zhaosg** [comment] 2017-06-09 05:33
I also encountered this problem, but I use the ionic3

**Comment by GodsFavoriteDeveloper** [comment] 2017-06-12 08:48
After installing this plugin i get the following but when i uninstall the plugin it hides :

Execution failed for task ':transformClassesWithDexForDebug'.
       [ > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;](url)

**Comment by cindyliu-yb** [comment] 2017-06-23 11:14
same problem here, any update?

**Comment by GodsFavoriteDeveloper** [comment] 2017-06-23 18:15
To fix this issue add the Android Support v4 plugin.  ionic cordova plugin add cordova-plugin-android-support-v4-jar

**Comment by Amit06** [comment] 2017-06-24 05:37
But this is what causing error .. adding this is causing problems in build

**Comment by KholofeloMoyaba** [comment] 2017-07-03 23:55
Same, issue. Any progress?
@regnete why is the android-support-v4-jar plugin needed to begin with?

**Comment by lordgreg** [comment] 2017-07-10 12:34
exactly the same issue. 

any updates?

**Comment by bethany77** [comment] 2017-07-11 15:35
Same issue with ionic3 ...
@regnete can you do something for us please ? It's a major bug ... Thanks in advance for your help !

**Comment by regnete** [comment] 2017-07-11 15:43
sorry to all of you. I don't have any experiences with ionic. anybody out there to fix this?

**Comment by lordgreg** [comment] 2017-07-12 12:02
This isn't actually an Ionic issue at all. Having a android platform created by cordova, using this plugin, the app start fails. Even if opening whole platform android folder in Android Studio, it crashes with the exact same issue.

I'll try to find something out. But... is there a reason to use the support library at all?

**Comment by regnete** [comment] 2017-07-12 12:40
I thought it is needed for accessibg the files via content provider api.

**Comment by mfossel** [comment] 2017-07-17 20:35
Same problem, would love to still use the plugin but I can't with cordova

**Comment by lordgreg** [comment] 2017-07-17 20:38
@mfossel and others..

I've made a fork (https://github.com/lordgreg/cordova-plugin-document-viewer/commit/bf498eb414c2a2226b6cfe3942297e78cf45a8ee) with nothing else than commenting the dependancy out of `plugin.xml`. Even without the dependency, I didn't encountered any crashes since I'm always checking if my os is android, and if so... I use file opener plugin to open the file using native App.

**Comment by regnete** [comment] 2017-07-18 06:45
I released and published version 0.9.4 of this plugin a few minutes ago.  It contains https://github.com/sitewaerts/cordova-plugin-document-viewer/pull/77 which should fix this issue. 

Could anybody please confirm?

@mfossel : Your fork should be obsolete now.

Thx for your patience!
And even more thx to @oddcb !

**Comment by stacybrenes** [comment] 2017-08-03 14:44
Hi Everyone, 

I run into this issue (`Execution failed for task ':transformClassesWithDexForDebug' `) often, with a variety of plugins when working with ionic. 
Go into your platforms/android/build.gradle  and change the default config from: 
`defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }
    }`

to:

`defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }

        multiDexEnabled true
    }`

What your doing is adding the `multiDexEnabled true` line after the if statement -- and your ionic project should build. 

NOTE: You will have to do this every time you remove/readd your android platform folder. 

Best of luck!

**Comment by regnete** [comment] 2017-08-03 18:03
I thought we fixed this issue. Does it still appear?

**Comment by lordgreg** [comment] 2017-08-03 18:08
@stacybrenes this is really a last-case scenario I would do. I'd rather stop using the plugin itself for a while than manually update the platform files.

But, however, this issue has been fixed with the latest version and should NOT appear anymore.

**Closed** 2023-08-21 06:13 UTC
Labels: bug, Platform: Android, Framework: ionic
