### ISSUE TITLE
ErrorNo viewer for application/pdf

### ISSUE THREAD

**Issue by naatogmagithub** [sitewaerts/cordova-plugin-document-viewer#15] opened 2016-01-18 11:31 UTC
I have a pdf document that I can open on my phone using its default app. When I tried to use this plugin to open it I got this error on the phone: "No viewer for application/pdf" and this "Error in SitewaertsDocumentViewer.viewDocument(): No viewer for application/pdf " in the console.

This is my code: 
document.addEventListener('deviceready', function () {
    // cordova.plugins.SitewaertsDocumentViewer is now available

    //click to view document.
$('#readfile').on('click', function(){
	SitewaertsDocumentViewer.viewDocument(
  "img/Website.pdf", "application/pdf", {
  	title: "Website Dev",
  	documentView: {closeLabel: "Close"},
  	navigationView: {closeLabel: "Close"},
  	email: {enabled: true},
  	print: {enabled: true},
  	openWith: {enabled: true},
  	search: {enabled: true}
   }, onShow, onClose, onMissingApp, onError);
});

}, false);

//callback functions
function onShow(){
	alert('Document shown.');
}
function onClose(){
	alert("Document closed.");
}
function onMissingApp(id, installer){
    if(confirm("Do you want to install the free PDF Viewer App "
            + appId + " for Android?")){
        installer();
    }
}
function onError(error){
  alert("Sorry! Cannot view document. Error: "+ error);
}

**Comment by regnete** [comment] 2016-01-18 14:43
Hi Ibrahim,

What ist the exact name of the pdf file? In your code it is writen as „img/Websitepdf“. Shouldn’t it be „img/Website.pdf“ (I added an obviuosly missing dot)? And you should always pass an absolute file uri, not a relative uri as you did. The error message may indicate, that the given file cannot be found.

Have a look at our sample app at https://github.com/sitewaerts/cordova-plugin-document-viewer-sample-app to get info about how to create absolute file uris.

If you still cannot fix the issue, please provide a little more information. Otherwise we are not able to track down the root cause of this issue.


-          Did the error occur on iPhone simulator or on a physical device? Simulator ist not supported by the plugin.


-          Which version of iOS do you use?



Sincerly

Felix

Von: IBRAHIM SAMAD [mailto:notifications@github.com]
Gesendet: Montag, 18. Januar 2016 12:32
An: sitewaerts/cordova-plugin-document-viewer <cordova-plugin-document-viewer@noreply.github.com>
Betreff: [cordova-plugin-document-viewer] ErrorNo viewer for application/pdf (#15)


I have a pdf document that I can open on my phone using its default app When I tried to use this plugin to open it I got this error on the phone: "No viewer for application/pdf" and this "Error in SitewaertsDocumentViewerviewDocument(): No viewer for application/pdf " in the console

This is my code:
documentaddEventListener('deviceready', function () {
// cordovapluginsSitewaertsDocumentViewer is now available

//click to view document

$('#readfile')on('click', function(){
SitewaertsDocumentViewerviewDocument(
"img/Websitepdf", "application/pdf", {
title: "Website Dev",
documentView: {closeLabel: "Close"},
navigationView: {closeLabel: "Close"},
email: {enabled: true},
print: {enabled: true},
openWith: {enabled: true},
search: {enabled: true}
}, onShow, onClose, onMissingApp, onError);
});

}, false);

//callback functions
function onShow(){
alert('Document shown');
}
function onClose(){
alert("Document closed");
}
function onMissingApp(id, installer){
if(confirm("Do you want to install the free PDF Viewer App "
+ appId + " for Android?")){
installer();
}
}
function onError(error){
alert("Sorry! Cannot view document Error: "+ error);
}

**Comment by naatogmagithub** [comment] 2016-01-18 15:15
I am using  android 4.4.2. I stored the file inside the image folder of the www folder. The name of the pdf file is Website. I added the extension .pdf since it is a pdf file.

**Comment by regnete** [comment] 2016-01-18 15:24
Hi Ibrahim,

thank you for the quick response. I didn’t recognise that you are running the plugin under android.

Anyway, you MUST pass in an absolute file uri pointing to the file in your www folder.

Have a look at our sample app for details (www/js/common.js). The sample app builds absolute uris to the www (a.k. „assets“)  folder like this;

var baseUrl = location.href.replace("/index.html", "");
function buildAssetsUrl(file)
{
    return baseUrl + "/" + file;
}


Von: IBRAHIM SAMAD [mailto:notifications@github.com]
Gesendet: Montag, 18. Januar 2016 16:16
An: sitewaerts/cordova-plugin-document-viewer <cordova-plugin-document-viewer@noreply.github.com>
Cc: Felix Schauerte <schauerte@sitewaerts.de>
Betreff: Re: [cordova-plugin-document-viewer] ErrorNo viewer for application/pdf (#15)


I am using android 4.4.2. I stored the file inside the image folder of the www folder. The name of the pdf file is Website. I added the extension .pdf since it is a pdf file.

**Comment by naatogmagithub** [comment] 2016-01-18 15:50
I have looked at the sample app, but I think that is too much for me. All I
needed is a button when clicked should open a pdf file named Website that
is stored in img of the www folder.

A help will be appreciated.

**Comment by regnete** [comment] 2016-01-18 15:52
Hi Ibrahim,

use the function I provided in my last email. That should work.

Felix


Von: IBRAHIM SAMAD [mailto:notifications@github.com]
Gesendet: Montag, 18. Januar 2016 16:50
An: sitewaerts/cordova-plugin-document-viewer <cordova-plugin-document-viewer@noreply.github.com>
Cc: Felix Schauerte <schauerte@sitewaerts.de>
Betreff: Re: [cordova-plugin-document-viewer] ErrorNo viewer for application/pdf (#15)

I have looked at the sample app, but I think that is too much for me. All I
needed is a button when clicked should open a pdf file named Website that
is stored in img of the www folder.

A help will be appreciated.

**Comment by naatogmagithub** [comment] 2016-01-18 16:15
Thanks too for your effort and time.

If I understand the code well, it means I should have something like this:

var baseUrl = location.href.replace("/index.html", "");
 function buildAssetsUrl(file) {
 return baseUrl + "/" + file;
}
var source = buildAssetsUrl("img/Website.pdf");

so that I can call it as SitewaertsDocumentViewer.viewDocument(source,
........)?

**Comment by regnete** [comment] 2016-01-18 16:16
jepp



Herzliche Grüße

Felix Schauerte
Dipl.-Wi.-Ing.
Geschäftsführung

Tel.:  +49 (221) 975 979 12
Mobil: +49 (173)  91 444 81
mailto:schauerte@sitewaerts.de<mailto:esch@sitewaerts.de>

Von: IBRAHIM SAMAD [mailto:notifications@github.com]
Gesendet: Montag, 18. Januar 2016 17:15
An: sitewaerts/cordova-plugin-document-viewer <cordova-plugin-document-viewer@noreply.github.com>
Cc: Felix Schauerte <schauerte@sitewaerts.de>
Betreff: Re: [cordova-plugin-document-viewer] ErrorNo viewer for application/pdf (#15)

Thanks too for your effort and time.

If I understand the code well, it means I should have something like this:

var baseUrl = location.href.replace("/index.html", "");
function buildAssetsUrl(file) {
return baseUrl + "/" + file;
}
var source = buildAssetsUrl("img/Website.pdf");

so that I can call it as SitewaertsDocumentViewer.viewDocument(source,
........)?


On Mon, Jan 18, 2016 at 7:52 AM, Felix Schauerte <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Hi Ibrahim,
>
> use the function I provided in my last email. That should work.
>
> Felix
>
>
> Von: IBRAHIM SAMAD [mailto:notifications@github.com]
> Gesendet: Montag, 18. Januar 2016 16:50
> An: sitewaerts/cordova-plugin-document-viewer <
> cordova-plugin-document-viewer@noreply.github.com<mailto:cordova-plugin-document-viewer@noreply.github.com>>
> Cc: Felix Schauerte <schauerte@sitewaerts.de<mailto:schauerte@sitewaerts.de>>
> Betreff: Re: [cordova-plugin-document-viewer] ErrorNo viewer for
> application/pdf (#15)
>
> I have looked at the sample app, but I think that is too much for me. All
> I
> needed is a button when clicked should open a pdf file named Website that
> is stored in img of the www folder.
>
> A help will be appreciated.
> On Jan 18, 2016 3:24 PM, "Felix Schauerte" <notifications@github.com
<mailto:notifications@github.com%0b>> <mailto:notifications@github.com>> wrote:
>
> > Hi Ibrahim,
> >
> > thank you for the quick response. I didn’t recognise that you are
> running
> > the plugin under android.
> >
> > Anyway, you MUST pass in an absolute file uri pointing to the file in
> your
> > www folder.
> >
> > Have a look at our sample app for details (www/js/common.js). The sample
> > app builds absolute uris to the www (a.k. „assets“) folder like this;
> >
> > var baseUrl = location.href.replace("/index.html", "");
> > function buildAssetsUrl(file)
> > {
> > return baseUrl + "/" + file;
> > }
> >
> >
> > Von: IBRAHIM SAMAD [mailto:notifications@github.com]
> > Gesendet: Montag, 18. Januar 2016 16:16
> > An: sitewaerts/cordova-plugin-document-viewer <
> > cordova-plugin-document-viewer@noreply.github.com<mailto<mailto:cordova-plugin-document-viewer@noreply.github.com%3cmailto>:
> cordova-plugin-document-viewer@noreply.github.com<mailto:cordova-plugin-document-viewer@noreply.github.com>>>
> > Cc: Felix Schauerte <schauerte@sitewaerts.de<mailto:
<mailto:schauerte@sitewaerts.de%3cmailto:%0b>> schauerte@sitewaerts.de<mailto:schauerte@sitewaerts.de>>>

**Comment by naatogmagithub** [comment] 2016-01-18 16:39
After I implemented that function, I had this error:

processMessage failed: Error: ReferenceError: appId is not defined cordova.js:1058
processMessage failed: Stack: ReferenceError: appId is not defined
    at onMissingApp (file:///android_asset/www/js/app.js:61:15)
    at canViewDocument.errorMsg (file:///android_asset/www/plugins/de.sitewaerts.cordova.documentviewer/www/sitewaertsdocumentviewer.js:273:29)
    at file:///android_asset/www/plugins/de.sitewaerts.cordova.documentviewer/www/sitewaertsdocumentviewer.js:179:33
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:292:54)
    at processMessage (file:///android_asset/www/cordova.js:1053:21)
    at androidExec.processMessages (file:///android_asset/www/cordova.js:1090:13) cordova.js:1059
processMessage failed: Message: S01 SitewaertsDocumentViewer660018634 {"status":0,"missingAppId":"de.sitewaerts.cleverdox.viewer"} 


This is my code, please just clean the mess for me. I am a beginner, sure I will understand later lol.

document.addEventListener('deviceready', function () {
    // cordova.plugins.SitewaertsDocumentViewer is now available

    //click to view document.
$('#readfile').on('click', function(){
	var source = buildAssetsUrl("img/lazy.pdf"); 
	SitewaertsDocumentViewer.viewDocument(
  	source, 'application/pdf', {
  	title: "Lazy loder",
  	documentView: {closeLabel: "Close"},
  	navigationView: {closeLabel: "Close"},
  	email: {enabled: true},
  	print: {enabled: true},
  	openWith: {enabled: true},
  	search: {enabled: true}
   }, onShow, onClose, onMissingApp, onError);
});

}, false);

var baseUrl = location.href.replace("/index.html", ""); 
 function buildAssetsUrl(file) { 
 return baseUrl + "/" + file; 
}


function onShow(){
	alert('Document shown.');
}
function onClose(){
	alert("Document closed.");
}
function onMissingApp(id, installer){
    if(confirm("Do you want to install the free PDF Viewer App "
            + appId + " for Android?")){
        installer();
    }
}
function onError(error){
  alert("Sorry! Cannot view document. Error: "+ error);
}

**Comment by regnete** [comment] 2016-01-18 18:19
Sorry Ibrahim,

I won't fix your typos. if you want to use open software, you have to learn the basics. Read some online tutorials about javascript coding and debugging. Currently your knowledge seems to be too low by far to build a stable and nice cordova app.

One last hint from me for your convenience:

As the error message says, you have to rename parameter 'id' at function 'onMissingApp' to 'appId'.

good night,

felix

Am 18.01.2016 um 17:39 schrieb IBRAHIM SAMAD <notifications@github.com<mailto:notifications@github.com>>:


After I implemented that function, I had this error:

processMessage failed: Error: ReferenceError: appId is not defined cordova.js:1058
processMessage failed: Stack: ReferenceError: appId is not defined
at onMissingApp (file:///android_asset/www/js/app.js:61:15)
at canViewDocument.errorMsg (file:///android_asset/www/plugins/de.sitewaerts.cordova.documentviewer/www/sitewaertsdocumentviewer.js:273:29)
at file:///android_asset/www/plugins/de.sitewaerts.cordova.documentviewer/www/sitewaertsdocumentviewer.js:179:33
at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:292:54)
at processMessage (file:///android_asset/www/cordova.js:1053:21)
at androidExec.processMessages (file:///android_asset/www/cordova.js:1090:13) cordova.js:1059
processMessage failed: Message: S01 SitewaertsDocumentViewer660018634 {"status":0,"missingAppId":"de.sitewaerts.cleverdox.viewer"}

This is my code, please just clean the mess for me. I am a beginner, sure I will understand later lol.

document.addEventListener('deviceready', function () {
// cordova.plugins.SitewaertsDocumentViewer is now available

//click to view document.


$('#readfile').on('click', function(){
var source = buildAssetsUrl("img/lazy.pdf");
SitewaertsDocumentViewer.viewDocument(
source, 'application/pdf', {
title: "Lazy loder",
documentView: {closeLabel: "Close"},
navigationView: {closeLabel: "Close"},
email: {enabled: true},
print: {enabled: true},
openWith: {enabled: true},
search: {enabled: true}
}, onShow, onClose, onMissingApp, onError);
});

}, false);

var baseUrl = location.href.replace("/index.html", "");
function buildAssetsUrl(file) {
return baseUrl + "/" + file;
}

function onShow(){
alert('Document shown.');
}
function onClose(){
alert("Document closed.");
}
function onMissingApp(id, installer){
if(confirm("Do you want to install the free PDF Viewer App "
+ appId + " for Android?")){
installer();
}
}
function onError(error){
alert("Sorry! Cannot view document. Error: "+ error);
}

-

**Comment by naatogmagithub** [comment] 2016-01-18 18:36
Of course am learning the basics.
Anyway thanks for that...

**Comment by regnete** [comment] 2016-01-18 19:30
keep on rocking

**Closed by regnete** 2016-01-18 19:30 UTC
