### ISSUE TITLE
Bottom page list with blank frames

### ISSUE THREAD

**Issue by tiagoAGA** [sitewaerts/cordova-plugin-document-viewer#44] opened 2017-01-24 14:49 UTC
Hello everyone.

Some PDF's that I open with the plugin on iOS 9.0, come with blank frames on bottom page list.

![image1](https://cloud.githubusercontent.com/assets/17410214/22251692/9ca06aa4-e243-11e6-83ed-14fe673b7275.PNG)

But when I select one blank page, the hightlight comes with the page frame

![image2](https://cloud.githubusercontent.com/assets/17410214/22251755/d980d710-e243-11e6-8ecf-21da5b05e904.PNG)

It happened with anyone?

Thank you for your support.

**Comment by regnete** [comment] 2017-01-24 15:19
We cannot reporoduce this issue. Does it occur only/always with certain/special pdf files? If yes, please provide one of them.

Does the issue occur on iOS >= 10.2  as well?

**Comment by tiagoAGA** [comment] 2017-01-24 15:33
Occurs always with certain pdf files. 
It seems the issues doesn't occur on iOS 10.2+. 

How can I send you an example?

**Comment by regnete** [comment] 2017-01-24 18:53
Plugin is just a wrapper arround the native ios pdf rendering api. So we have very limited influence on the rendering process. As the issue is fixed in iOS 10.2+, we won't fix it. Please let your customers update theiri devices to iOS 10.2+.

**Closed by regnete** 2017-01-24 18:53 UTC
Labels: Platform: iOS, wontfix
