### ISSUE TITLE
iOS 11 ThumbsView performance

### ISSUE THREAD

**Issue by ustadbb** [sitewaerts/cordova-plugin-document-viewer#82] opened 2017-09-24 16:27 UTC
the thumbView seems to suffer from massive performance decrease on iOS 11
for pdf documents with more than 100 pages.

pressing the thumb button in main toolbar blocks the app until the thumbView
finally displays 

- the same build on iOS 10 renders the thumbView nearly immediately
- on iOS 11 it takes minutes to render the thumbView

this problem occurs both on real devices and simulators with iOS 11

OS: iOS 11

**Comment by regnete** [comment] 2017-10-11 10:00
did you discover any additional performance problems running at ios 11?

**Comment by ustadbb** [comment] 2017-10-11 11:19
no - otherwise performance seems ok.

the problem only occurs with iOS11 - on physical devices and simulators.
Hard to say the exact amount of pages to slowdown the thumbview - seems round about 150 and more pages.

A test with the "original" VFRReader ion iOS11 doesn't slowdown the thumbview. 
Meanwhile i've worked around the problem by hiding the thumbview button for pdfs with pagecount > 130 but that's hopefully only a temporary work around.

used for the building:
-  Xcode Version 9.0
- iOS Deployment Target iOS 9.0
- Compiler Default compiler (Apple LLVM 9.0)
iPad Air 2 (11.0)

**Comment by NonnEmilia** [comment] 2017-10-25 06:20
Debugging the plugin I found this problem may be related to this: https://openradar.appspot.com/35125028

It seems Apple has changed the [`CGPDFDocumentGetPage`](https://developer.apple.com/documentation/coregraphics/1402586-cgpdfdocumentgetpage) method behaviour in iOS 11 affecting performance.

This method is called in a `for` loop here: https://github.com/sitewaerts/cordova-plugin-document-viewer/blob/2753035014ef04732e7f936644dd71e7e503b2f9/src/ios/vfr/ReaderDocumentOutline.m#L297

Any idea for a fix? I found [this](https://twitter.com/lieven/status/922489725444853760), but I don't know how to manipulate the catalog found with the [`CGPDFDocumentGetCatalog`](https://developer.apple.com/documentation/coregraphics/1402606-cgpdfdocumentgetcatalog?language=objc) method...

**Comment by regnete** [comment] 2017-10-25 14:52
We are currently working on a fix for this issue. Thx for your input!

**Comment by Livven** [comment] 2017-10-25 17:20
The problem is actually not with the thumbnail view itself but the table of contents. Specifically, the slowdown occurs in `ReaderDocumentOutline.outlineItems` which is unchanged from the original implementation in VFRReader, the only difference is that VFRReader doesn't actually call that method since it does not display the table of contents.

A possible workaround would be to delay calling that method until it's actually needed, i.e. when the user switches from the thumbnail view to the TOC view.

**Comment by Livven** [comment] 2017-10-27 17:25
It's [fixed](https://github.com/sitewaerts/cordova-plugin-document-viewer/commits/feature/thumbnail-view-slowdown-fix) now, just waiting for @regnete to merge and publish.

@NonnEmilia You were a step ahead of me there and of course absolutely right, `CGPDFDocumentGetPage` was indeed the problem. In case you're curious, most calls to it were unnecessary anyway since they were in a nested loop for each page *and* TOC entry. Now it's only called once for each page for the first TOC entry and the result is cached for later ones.

There is still a small delay (way smaller than without the fix, but still bigger than on iOS 10) that becomes noticeable as the number of pages or TOC entries grows very large. However I don't see any more calls to `CGPDFDocumentGetPage` that could be cached and reused so a fix for that would require a different approach, possibly using the document catalog as you mentioned.

**Comment by regnete** [comment] 2017-11-02 09:14
fixed in version 0.9.6

**Closed by regnete** 2017-11-02 09:14 UTC
Labels: Platform: iOS
